language: python

python:
- 3.8

before_install:
- curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py > /tmp/get-poetry.py
- python /tmp/get-poetry.py --preview --yes
- source $HOME/.poetry/env

install:
- poetry install -E yaml -E console

script:
- poetry run pytest

after_success:
- poetry build
- poetry publish
